---
extends: "eslint:recommended"
env:
  browser: true
  node: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
globals:
  Reveal: true
rules:
  # Syntax
  no-caller: 2
  no-eval: 2
  no-labels: 2
  no-else-return: 2
  no-div-regex: 2
  no-case-declarations: 2
  no-new: 2
  no-useless-call: 2
  vars-on-top: 2
  valid-jsdoc: 2
  semi:
    - 2
    - "always"
  dot-location:
    - 2
    - "property"
  dot-notation: 2
  guard-for-in: 2
  no-new-symbol: 2
  no-const-assign: 2
  # Style
  block-spacing:
    - 2
    - "always"
  brace-style:
    - 2
    - "1tbs"
  spaced-comment:
    - 2
    - "always"
  comma-spacing:
    - 2
    -
      before: false
      after: true
  keyword-spacing: 2
  eol-last: 2
  func-names: 2
  func-style:
    - 2
    - "declaration"
    -
      allowArrowFunctions: true
  key-spacing:
    - 2
    -
      beforeColon: false
      afterColon: true
  semi-spacing:
    - 2
    -
      before: false
      after: true
  space-before-blocks: 2
  space-before-function-paren:
    - 2
    - "never"
  space-infix-ops: 2
  arrow-spacing: 2
  generator-star-spacing:
    - 2
    -
      before: false
      after: true
  no-confusing-arrow: 2
  prefer-reflect: 2
  prefer-rest-params: 2
  prefer-spread: 1
  prefer-template: 0
  require-yield: 2
