baseurl = "https://www.chrisdeluca.me"
languageCode = "en-us"
title = "Chris DeLuca"
theme = "novel"
PygmentsCodeFences = true
enableRobotsTXT = true
pygmentsuseclasses = true
enableEmoji = true
menus = [ "main", "footer" ]
paginate = 20
rssLimit = 50

[author]
  name = "Chris DeLuca"
  email = "contact@chrisdeluca.me"
  photo = "/images/chris-portrait.jpeg"
  region = "New York"
  nickname = "bronzehedwick"
  pronouns = "he/him"
  identities = ["writer", "improviser", "software developer"]
  [author.key]
    id = "57B2F2C5"
    url = "/files/chris-deluca-pgp.pub.asc"

[taxonomies]
  category = "categories"
  topic = "topics"
  series = "series"

[outputFormats.MICRO]
  MediaType = "application/rss+xml"
  BaseName = "micro"
  IsHTML = false
  IsPlainText = true
  noUgly = true
  Rel = "alternate"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON", "CSV", "MICRO"]

[[menu.main]]
  name = "About me"
  url = "/page/about"
  weight = 30

[[menu.main]]
  name = "Articles"
  url = "/article"
  weight = 40

[[menu.main]]
  name = "Notes"
  url = "/note"
  weight = 45

[[menu.main]]
  name = "Feeds"
  url = "/feeds"
  weight = 100

[params]
  description = "Chris DeLuca's webbed site"
  mainSections = ["article", "note"]

  [params.categoryEmoji.reading]
    url = "/categories/reading"
    icon = "📚"

  [params.categoryEmoji.writing]
    url = "/categories/writing"
    icon = "📝"

  [params.categoryEmoji.movies]
    url = "/categories/movies"
    icon = "🍿"

  [params.categoryEmoji.music]
    url = "/categories/music"
    icon = "🎵"

  [params.categoryEmoji.cats]
    url = "/categories/cats"
    icon = "🐈"

  [params.categoryEmoji.games]
    url = "/categories/games"
    icon = "🕹️"

  [params.categoryEmoji.tv]
    url = "/categories/tv"
    icon = "📺"

  [params.categoryEmoji.podcasting]
    url = "/categories/podcasting"
    icon = "🎙️"

  [params.categoryEmoji.quotes]
    url = "/categories/quotes"
    icon = "💬"

  [params.categoryEmoji.drawing]
    url = "/categories/drawing"
    icon = "🎨"

  [params.categoryEmoji.photos]
    url = "/categories/photos"
    icon = "📷"

  [params.categoryEmoji.tech]
    url = "/categories/tech"
    icon = "💻"

  [params.categoryEmoji.improv]
    url = "/categories/improv"
    icon = "🐵"

  [params.categoryEmoji.health]
    url = "/categories/health"
    icon = "🏥"

  [params.socialLinks.twitter]
    name = "🐦 Twitter"
    url = "https://twitter.com/chrisjohndeluca"
    icon = "svg/twitter.html"
    weight = 50
    featured = true

  [params.socialLinks.mastodon]
    name = "🐘 Mastodon"
    url = "https://mastodon.social/@bronzehedwick"
    weight = 40
    featured = false

  [params.socialLinks.stackoverflow]
    name = "🥞 StackOverflow"
    url = "http://stackoverflow.com/users/1143575/bronzehedwick"
    icon = "svg/stack-overflow.html"
    weight = 31
    featured = false

  [params.socialLinks.drupal]
    name = "💧 Drupal"
    url = "https://www.drupal.org/u/bronzehedwick"
    icon = "svg/drupal.html"
    weight = 12
    featured = false

  [params.socialLinks.sourcehut]
    name = "◯ sourcehut"
    url = "https://sr.ht/~bronzehedwick/"
    weight = 44
    featured = false

  [params.socialLinks.github]
    name = "🐙 Github"
    url = "https://github.com/bronzehedwick"
    icon = "svg/github.html"
    weight = 45
    featured = true

  [params.socialLinks.pinboard]
    name = "📌 Pinboard"
    url = "https://pinboard.in/u:bronzehedwick"
    icon = ""
    weight = 30
    featured = false

  [params.socialLinks.newsblur]
    name = "🗞 Newsblur"
    url = "http://bronzehedwick.newsblur.com/"
    color = "#e6af4c"
    icon = ""
    weight = 25
    featured = false

  [params.socialLinks.keybase]
    name = "🗝 Keybase"
    url = "https://keybase.io/bronzehedwick"
    icon = "svg/keybase.html"
    weight = 43
    featured = true

  [params.socialLinks.youtube]
    name = "📺 YouTube"
    url = "https://www.youtube.com/channel/UChfcp3RhN0FJOnTZquDRzYw"
    icon = "svg/youtube.html"
    weight = 35
    featured = true

  [params.socialLinks.instagram]
    name = "📷 Instagram"
    url = "https://www.instagram.com/bronzehedwick/"
    icon = "svg/instagram.html"
    weight = 40
    featured = true

  [params.socialLinks.reddit]
    name = "🐰 Reddit"
    url = "https://www.reddit.com/user/bronzehedwick"
    color = "#0976b4"
    icon = ""
    weight = 15
    featured = false

  [params.socialLinks.linkedin]
    name = "📋 LinkedIn"
    url = "https://www.linkedin.com/in/christopherdeluca"
    color = "#0976b4"
    icon = ""
    weight = -50
    featured = false

  [params.socialLinks.hackernews]
    name = "👾 Hacker News"
    url = "https://news.ycombinator.com/user?id=bronzehedwick"
    color = "#ff6600"
    icon = ""
    weight = 10

  [params.socialLinks.codepen]
    name = "🎆 CodePen"
    url = "https://codepen.io/bronzehedwick/"
    color = "#000"
    icon = ""
    weight = 8

  [params.socialLinks.devto]
    name = "🖲 dev.to"
    url = "https://dev.to/bronzehedwick"
    color = "#000"
    icon = ""
    weight = 20

  [params.socialLinks.microblog]
    name = "💬 micro.blog"
    url = "https://micro.blog/chrisd"
    color = "#fd9526"
    icon = ""
    weight = 20

  [params.socialLinks.lobsters]
    name = "🦞 lobsters"
    url = "https://lobste.rs/u/bronzehedwick"
    color = "#0f0"
    icon = ""
    weight = 20

  [params.socialLinks.letterboxd]
    name = "🎥 Letterboxd"
    url = "https://letterboxd.com/bronzehedwick/"
    color = "#14181c"
    icon = ""
    weight = 3

  [params.socialLinks.thestorygraph]
    name = "📚 The StoryGraph"
    url = "https://app.thestorygraph.com/profile/bronzehedwick"
    color = "#3B82F6"
    icon = ""
    weight = 4

  [params.socialLinks.discogs]
    name = "📀 Discogs"
    url = "https://www.discogs.com/user/bronzehedwick"
    color = "#111"
    icon = ""
    weight = 5

[markup.goldmark.renderer]
unsafe = true
