#!/usr/local/bin/node
/* vim: set ft=javascript */
/* eslint-disable no-console */

'use strict';

const http = require('http');
const crypto = require('crypto');
const credentials = require('../credentials.json');
const exec = require('child_process').exec;

function writeResponse(status = 200, message = 'OK', response) {
  response.writeHead(status, {'Content-Type': 'text/plain'});
  response.end(`${message}
  `);
  return status;
}

http.createServer(function server(request, response) {
  let body = [];

  request.on('error', error => {
    // Something went wrong, so log it and return a http error code.
    console.log(error);
    return writeResponse(500, 'Error', response);
  }).on('data', chunk => {
    // This is the method the node js docs recommend to parse POST bodies.
    body.push(chunk);
  }).on('end', () => {
    // Parse the body as a string.
    const bodyStr = Buffer.concat(body).toString();

    // Exit early if there is not request body.
    if (!bodyStr) {
      return writeResponse(500, 'No request body', response);
    }

    // Parse the body as json.
    const json = JSON.parse(bodyStr);

    // Exit early if a push wasn't on the master branch.
    if (json.ref !== 'refs/heads/master') {
      return writeResponse(202, 'Only master branch pushes allowed to build', response);
    }

    const signature = request.headers['x-hub-signature'];
    // Exit early if there is no signature
    if (!signature) {
      return writeResponse(500, 'No signature', response);
    }

    const repoVars = credentials[json.repository.full_name];
    const {secret, buildCmd, path} = repoVars;

    const cryptoAlgorithm = request.headers['x-hub-signature'].match(/.+?(?==)/)[0];
    const hmac = crypto.createHmac(cryptoAlgorithm, secret);

    // Generate a digest of the body.
    hmac.update(bodyStr);
    const digest = hmac.digest('hex');

    if (`${cryptoAlgorithm}=${digest}` === signature) {
      const buildCmds = [
        'git reset --hard',
        'git pull origin master',
        `rm -rf ${path.build}`,
        buildCmd,
        `rsync -av --progress --delete ${path.build}/ ${path.dest}`
      ];

      // Actually build the site.
      exec(buildCmds.join(' && '), {
        cwd: path.src,
        env: {
          NODE_ENV: 'production'
        }
      }, (error, stdout, stderr) => {
        if (error) console.error(error);
        if (stderr) console.error(stderr);
        console.log(stdout);
        return writeResponse(500, 'Something went wrong', response);
      });

      return writeResponse(200, 'OK', response);
    }

    // The signature was bad; denied.
    return writeResponse(403, 'Permission denied', response);

  });

}).listen(9826);
