#!/bin/sh
# Sync new web server configuration.

# Where the remote webserver expects the site.
SERVE=/usr/local/www/

# Sync the Caddyfile.
scp Caddyfile "chrishost:$SERVE/Caddyfile"

# Restart the web server.
ssh chrishost "sudo service caddy restart"
