#!/usr/local/bin/node

const path = require('path');
const fs = require('fs');
const validator = require('html-validator');
let options = {
 format: 'text',
 ingore: 'Warning: Consider using the “h1” element as a top-level heading only (all “h1” elements are treated as top-level headings by many screen readers and other tools).'
};

// Recurse down a directory tree to find all files,
// potentially of a certain type.
function walk(directoryName) {
  // Read in the given directory to loop over.
  fs.readdir(directoryName, (error, files) => {
    if (error) {
      throw error;
    }

    // Loop over the resulting files.
    files.forEach(file => {
      // Get the absolute path, so stat won't fail.
      const fullPath = path.join(directoryName, file);

      // Get the file system info for the file.
      fs.stat(fullPath, (error, stat) => {
        if (error) {
          throw error;
        }

        if (stat.isDirectory()) {
          // If the file is a directory, recurse down it.
          walk(fullPath);
        }
        else {
          // Make sure we only validate html files.
          if (path.extname(fullPath) === '.html') {
            // File is a regular file, so add to the output array.
            fs.readFile(fullPath, 'utf8', (error, html) => {
              if (error) {
                throw error;
              }

              // Assign this files contents to the
              // options to pass into be validated.
              options.data = html;

              validator(options)
                .then(data => {
                  // Show the title of the page being validated.
                  console.log(fullPath);

                  // Show the validation data.
                  console.log(data);
                })
                .catch(error => {
                  console.error(error);
                });
            });
          }
        }
      })
    });
  });
}

walk('public');
